### ISSUE TITLE
Possible to use more than 5 Bon-IDs

### ISSUE THREAD

**Issue by macinsight** [Craze1997/grocy-rewe-connect#2]
Moin,

es ist moeglich, mehr als nur die angezeigten 5 Bon-IDs zu verwenden.

To reporoduce:
Log in with RSTP Token
When asked which Bon to import, enter something not between 0-4, e.g. 20.
Content of Bon #20 will be printed to stdout.

**Comment by Craze1997** [comment]
Ich habe die Eingabe limitiert. Außerdem habe ich der config einen neuen Parameter gegeben, womit sich die Anzahl der abzurufenen Bons einstellen lässt.
