### ISSUE TITLE
Fetch RSTP Cookie from Browser without user interaction

### ISSUE THREAD

**Issue by macinsight** [Craze1997/grocy-rewe-connect#4]
It'd be nice if we didn't have to log in every time we run the script and instea fetched the token from the browser. A tool to accomplish that could be this: https://github.com/borisbabic/browser_cookie3

**Comment by macinsight** [comment]
Added a branch on my fork to track this: https://github.com/macinsight/grocy-rewe-connect/tree/feat/fetch-cookie

**Comment by Craze1997** [comment]
I tried this myself before. problem was the WAF from REWE. If you find a way for this, let me know.
