### ISSUE TITLE
Use external grocy API client instead of self-built

### ISSUE THREAD

**Issue by macinsight** [Craze1997/grocy-rewe-connect#5]
t might be beneficial to switch out the homegrown API client for something a bit more robust, i.e. [pygrocy](https://github.com/SebRut/pygrocy).

**Comment by Craze1997** [comment]
Ich wüsste nicht, inwiefern das Mehrwert bieten würde.

**Comment by macinsight** [comment]
Weniger Arbeit für Dich, weil Du die Grocy-API nicht selber wrappen müsstest. Kann aber auch zu, theoretisch.
